// /country-info.js —— 自動生成（依 world.svg 標題鍵名對應）
window.COUNTRY_INFO = {
  "Andorra"                                 : { zhName: "Andorra", currencyCode: "EUR", currencyName: "歐元", iso2: "AD" },
  "United Arab Emirates"                    : { zhName: "United Arab Emirates", currencyCode: "AED", currencyName: "迪拉姆", iso2: "AE" },
  "Afghanistan"                             : { zhName: "Afghanistan", currencyCode: "AFN", currencyName: "阿富汗尼", iso2: "AF" },
  "Antigua and Barbuda"                     : { zhName: "Antigua and Barbuda", currencyCode: "USD", currencyName: "美元", iso2: "AG" },
  "Anguilla"                                : { zhName: "Anguilla", currencyCode: "XCD", currencyName: "東加勒比元", iso2: "AI" },
  "Albania"                                 : { zhName: "Albania", currencyCode: "ALL", currencyName: "列克", iso2: "AL" },
  "Armenia"                                 : { zhName: "Armenia", currencyCode: "AMD", currencyName: "德拉姆", iso2: "AM" },
  "Angola"                                  : { zhName: "Angola", currencyCode: "AOA", currencyName: "寬扎", iso2: "AO" },
  "Argentina"                               : { zhName: "Argentina", currencyCode: "USD", currencyName: "美元", iso2: "AR" },
  "American Samoa"                          : { zhName: "American Samoa", currencyCode: "USD", currencyName: "美元", iso2: "AS" },
  "Austria"                                 : { zhName: "Austria", currencyCode: "EUR", currencyName: "歐元", iso2: "AT" },
  "Australia"                               : { zhName: "Australia", currencyCode: "AUD", currencyName: "澳幣", iso2: "AU" },
  "Aruba"                                   : { zhName: "Aruba", currencyCode: "AWG", currencyName: "阿魯巴弗羅林", iso2: "AW" },
  "Aland Islands"                           : { zhName: "Aland Islands", currencyCode: "EUR", currencyName: "歐元", iso2: "AX" },
  "Azerbaijan"                              : { zhName: "Azerbaijan", currencyCode: "AZN", currencyName: "馬納特", iso2: "AZ" },
  "Bosnia and Herzegovina"                  : { zhName: "Bosnia and Herzegovina", currencyCode: "BAM", currencyName: "可兌換馬克", iso2: "BA" },
  "Barbados"                                : { zhName: "Barbados", currencyCode: "USD", currencyName: "美元", iso2: "BB" },
  "Bangladesh"                              : { zhName: "Bangladesh", currencyCode: "BDT", currencyName: "塔卡", iso2: "BD" },
  "Belgium"                                 : { zhName: "Belgium", currencyCode: "EUR", currencyName: "歐元", iso2: "BE" },
  "Burkina Faso"                            : { zhName: "Burkina Faso", currencyCode: "XOF", currencyName: "西非法郎", iso2: "BF" },
  "Bulgaria"                                : { zhName: "Bulgaria", currencyCode: "BGN", currencyName: "列弗", iso2: "BG" },
  "Bahrain"                                 : { zhName: "Bahrain", currencyCode: "BHD", currencyName: "巴林第納爾", iso2: "BH" },
  "Burundi"                                 : { zhName: "Burundi", currencyCode: "BIF", currencyName: "蒲隆地法郎", iso2: "BI" },
  "Benin"                                   : { zhName: "Benin", currencyCode: "XOF", currencyName: "西非法郎", iso2: "BJ" },
  "Saint Barthelemy"                        : { zhName: "Saint Barthelemy", currencyCode: "EUR", currencyName: "歐元", iso2: "BL" },
  "Brunei Darussalam"                       : { zhName: "Brunei Darussalam", currencyCode: "BND", currencyName: "汶萊元", iso2: "BN" },
  "Bolivia"                                 : { zhName: "Bolivia", currencyCode: "USD", currencyName: "美元", iso2: "BO" },
  "Bermuda"                                 : { zhName: "Bermuda", currencyCode: "USD", currencyName: "美元", iso2: "BM" },
  "Bonaire,  Saint Eustachius and Saba"     : { zhName: "Bonaire,  Saint Eustachius and Saba", currencyCode: "USD", currencyName: "美元", iso2: "BQ" },
  "Brazil"                                  : { zhName: "Brazil", currencyCode: "USD", currencyName: "美元", iso2: "BR" },
  "Bahamas"                                 : { zhName: "Bahamas", currencyCode: "USD", currencyName: "美元", iso2: "BS" },
  "Bhutan"                                  : { zhName: "Bhutan", currencyCode: "BTN", currencyName: "努爾特魯姆", iso2: "BT" },
  "Bouvet Island"                           : { zhName: "Bouvet Island", currencyCode: "NOK", currencyName: "挪威克朗", iso2: "BV" },
  "Botswana"                                : { zhName: "Botswana", currencyCode: "BWP", currencyName: "普拉", iso2: "BW" },
  "Belarus"                                 : { zhName: "Belarus", currencyCode: "BYN", currencyName: "白俄盧布", iso2: "BY" },
  "Belize"                                  : { zhName: "Belize", currencyCode: "USD", currencyName: "美元", iso2: "BZ" },
  "Canada"                                  : { zhName: "Canada", currencyCode: "USD", currencyName: "美元", iso2: "CA" },
  "Cocos  (Keeling)  Islands"               : { zhName: "Cocos  (Keeling)  Islands", currencyCode: "AUD", currencyName: "澳幣", iso2: "CC" },
  "Democratic Republic of Congo"            : { zhName: "Democratic Republic of Congo", currencyCode: "CDF", currencyName: "剛果法郎", iso2: "CD" },
  "Central African Republic"                : { zhName: "Central African Republic", currencyCode: "XAF", currencyName: "中非法郎", iso2: "CF" },
  "Republic of Congo"                       : { zhName: "Republic of Congo", currencyCode: "XAF", currencyName: "中非法郎", iso2: "CG" },
  "Switzerland"                             : { zhName: "Switzerland", currencyCode: "CHF", currencyName: "瑞士法郎", iso2: "CH" },
  "Côte d'Ivoire"                           : { zhName: "Côte d'Ivoire", currencyCode: "XOF", currencyName: "西非法郎", iso2: "CI" },
  "Cook Islands"                            : { zhName: "Cook Islands", currencyCode: "NZD", currencyName: "紐幣", iso2: "CK" },
  "Chile"                                   : { zhName: "Chile", currencyCode: "USD", currencyName: "美元", iso2: "CL" },
  "Cameroon"                                : { zhName: "Cameroon", currencyCode: "XAF", currencyName: "中非法郎", iso2: "CM" },
  "China"                                   : { zhName: "China", currencyCode: "CNY", currencyName: "人民幣", iso2: "CN" },
  "Colombia"                                : { zhName: "Colombia", currencyCode: "USD", currencyName: "美元", iso2: "CO" },
  "Costa Rica"                              : { zhName: "Costa Rica", currencyCode: "USD", currencyName: "美元", iso2: "CR" },
  "Cuba"                                    : { zhName: "Cuba", currencyCode: "CUP", currencyName: "美元", iso2: "CU" },
  "Cape Verde"                              : { zhName: "Cape Verde", currencyCode: "CVE", currencyName: "埃斯庫多", iso2: "CV" },
  "Curaçao"                                 : { zhName: "Curaçao", currencyCode: "ANG", currencyName: "荷屬安替列盾", iso2: "CW" },
  "Christmas Island"                        : { zhName: "Christmas Island", currencyCode: "AUD", currencyName: "澳幣", iso2: "CX" },
  "Cyprus"                                  : { zhName: "Cyprus", currencyCode: "EUR", currencyName: "歐元", iso2: "CY" },
  "Czech Republic"                          : { zhName: "Czech Republic", currencyCode: "CZK", currencyName: "捷克克朗", iso2: "CZ" },
  "Germany"                                 : { zhName: "Germany", currencyCode: "EUR", currencyName: "歐元", iso2: "DE" },
  "Djibouti"                                : { zhName: "Djibouti", currencyCode: "DJF", currencyName: "吉布地法郎", iso2: "DJ" },
  "Denmark"                                 : { zhName: "Denmark", currencyCode: "DKK", currencyName: "丹麥克朗", iso2: "DK" },
  "Dominica"                                : { zhName: "Dominica", currencyCode: "USD", currencyName: "美元", iso2: "DM" },
  "Dominican Republic"                      : { zhName: "Dominican Republic", currencyCode: "USD", currencyName: "美元", iso2: "DO" },
  "Algeria"                                 : { zhName: "Algeria", currencyCode: "DZD", currencyName: "阿爾及利亞第納爾", iso2: "DZ" },
  "Ecuador"                                 : { zhName: "Ecuador", currencyCode: "USD", currencyName: "美元", iso2: "EC" },
  "Egypt"                                   : { zhName: "Egypt", currencyCode: "EGP", currencyName: "埃及鎊", iso2: "EG" },
  "Estonia"                                 : { zhName: "Estonia", currencyCode: "EUR", currencyName: "歐元", iso2: "EE" },
  "Western Sahara"                          : { zhName: "Western Sahara", currencyCode: "MAD", currencyName: "摩洛哥迪拉姆", iso2: "EH" },
  "Eritrea"                                 : { zhName: "Eritrea", currencyCode: "ERN", currencyName: "納克法", iso2: "ER" },
  "Spain"                                   : { zhName: "Spain", currencyCode: "EUR", currencyName: "歐元", iso2: "ES" },
  "Ethiopia"                                : { zhName: "Ethiopia", currencyCode: "ETB", currencyName: "比爾", iso2: "ET" },
  "Finland"                                 : { zhName: "Finland", currencyCode: "EUR", currencyName: "歐元", iso2: "FI" },
  "Fiji"                                    : { zhName: "Fiji", currencyCode: "FJD", currencyName: "斐濟元", iso2: "FJ" },
  "Falkland Islands"                        : { zhName: "Falkland Islands", currencyCode: "USD", currencyName: "美元", iso2: "FK" },
  "Federated States of Micronesia"          : { zhName: "Federated States of Micronesia", currencyCode: "USD", currencyName: "美元", iso2: "FM" },
  "Faroe Islands"                           : { zhName: "Faroe Islands", currencyCode: "DKK", currencyName: "丹麥克朗", iso2: "FO" },
  "France"                                  : { zhName: "France", currencyCode: "EUR", currencyName: "歐元", iso2: "FR" },
  "Gabon"                                   : { zhName: "Gabon", currencyCode: "XAF", currencyName: "中非法郎", iso2: "GA" },
  "United Kingdom"                          : { zhName: "United Kingdom", currencyCode: "GBP", currencyName: "英鎊", iso2: "GB" },
  "Georgia"                                 : { zhName: "Georgia", currencyCode: "GEL", currencyName: "拉里", iso2: "GE" },
  "Grenada"                                 : { zhName: "Grenada", currencyCode: "USD", currencyName: "美元", iso2: "GD" },
  "French Guiana"                           : { zhName: "French Guiana", currencyCode: "USD", currencyName: "美元", iso2: "GF" },
  "Guernsey"                                : { zhName: "Guernsey", currencyCode: "GGP", currencyName: "根西鎊", iso2: "GG" },
  "Ghana"                                   : { zhName: "Ghana", currencyCode: "GHS", currencyName: "塞地", iso2: "GH" },
  "Gibraltar"                               : { zhName: "Gibraltar", currencyCode: "GIP", currencyName: "直布羅陀鎊", iso2: "GI" },
  "Greenland"                               : { zhName: "Greenland", currencyCode: "DKK", currencyName: "丹麥克朗", iso2: "GL" },
  "Gambia"                                  : { zhName: "Gambia", currencyCode: "GMD", currencyName: "達拉西", iso2: "GM" },
  "Guinea"                                  : { zhName: "Guinea", currencyCode: "GNF", currencyName: "幾內亞法郎", iso2: "GN" },
  "Glorioso Islands"                        : { zhName: "Glorioso Islands", currencyCode: "EUR", currencyName: "歐元", iso2: "TF-GO" },
  "Guadeloupe"                              : { zhName: "Guadeloupe", currencyCode: "EUR", currencyName: "歐元", iso2: "GP" },
  "Equatorial Guinea"                       : { zhName: "Equatorial Guinea", currencyCode: "XAF", currencyName: "中非法郎", iso2: "GQ" },
  "Greece"                                  : { zhName: "Greece", currencyCode: "EUR", currencyName: "歐元", iso2: "GR" },
  "South Georgia and South Sandwich Islands": { zhName: "South Georgia and South Sandwich Islands", currencyCode: "GBP", currencyName: "英鎊", iso2: "GS" },
  "Guatemala"                               : { zhName: "Guatemala", currencyCode: "USD", currencyName: "美元", iso2: "GT" },
  "Guam"                                    : { zhName: "Guam", currencyCode: "USD", currencyName: "美元", iso2: "GU" },
  "Guinea-Bissau"                           : { zhName: "Guinea-Bissau", currencyCode: "XOF", currencyName: "西非法郎", iso2: "GW" },
  "Guyana"                                  : { zhName: "Guyana", currencyCode: "USD", currencyName: "美元", iso2: "GY" },
  "Hong Kong"                               : { zhName: "Hong Kong", currencyCode: "HKD", currencyName: "港幣", iso2: "HK" },
  "Heard Island and McDonald Islands"       : { zhName: "Heard Island and McDonald Islands", currencyCode: "AUD", currencyName: "澳幣", iso2: "HM" },
  "Honduras"                                : { zhName: "Honduras", currencyCode: "USD", currencyName: "美元", iso2: "HN" },
  "Croatia"                                 : { zhName: "Croatia", currencyCode: "EUR", currencyName: "歐元", iso2: "HR" },
  "Haiti"                                   : { zhName: "Haiti", currencyCode: "USD", currencyName: "美元", iso2: "HT" },
  "Hungary"                                 : { zhName: "Hungary", currencyCode: "HUF", currencyName: "福林", iso2: "HU" },
  "Indonesia"                               : { zhName: "Indonesia", currencyCode: "IDR", currencyName: "印尼盾", iso2: "ID" },
  "Ireland"                                 : { zhName: "Ireland", currencyCode: "EUR", currencyName: "歐元", iso2: "IE" },
  "Israel"                                  : { zhName: "Israel", currencyCode: "ILS", currencyName: "新謝克爾", iso2: "IL" },
  "Isle of Man"                             : { zhName: "Isle of Man", currencyCode: "IMP", currencyName: "曼島鎊", iso2: "IM" },
  "India"                                   : { zhName: "India", currencyCode: "INR", currencyName: "盧比", iso2: "IN" },
  "British Indian Ocean Territory"          : { zhName: "British Indian Ocean Territory", currencyCode: "USD", currencyName: "美元", iso2: "IO" },
  "Iraq"                                    : { zhName: "Iraq", currencyCode: "IQD", currencyName: "伊拉克第納爾", iso2: "IQ" },
  "Iran"                                    : { zhName: "Iran", currencyCode: "IRR", currencyName: "伊朗里亞爾", iso2: "IR" },
  "Iceland"                                 : { zhName: "Iceland", currencyCode: "ISK", currencyName: "冰島克朗", iso2: "IS" },
  "Italy"                                   : { zhName: "Italy", currencyCode: "EUR", currencyName: "歐元", iso2: "IT" },
  "Jersey"                                  : { zhName: "Jersey", currencyCode: "JEP", currencyName: "澤西鎊", iso2: "JE" },
  "Jamaica"                                 : { zhName: "Jamaica", currencyCode: "USD", currencyName: "美元", iso2: "JM" },
  "Jordan"                                  : { zhName: "Jordan", currencyCode: "JOD", currencyName: "約旦第納爾", iso2: "JO" },
  "Japan"                                   : { zhName: "Japan", currencyCode: "JPY", currencyName: "日圓", iso2: "JP" },
  "Juan De Nova Island"                     : { zhName: "Juan De Nova Island", currencyCode: "EUR", currencyName: "歐元", iso2: "TF-JU" },
  "Kenya"                                   : { zhName: "Kenya", currencyCode: "KES", currencyName: "先令", iso2: "KE" },
  "Kyrgyzstan"                              : { zhName: "Kyrgyzstan", currencyCode: "KGS", currencyName: "索姆", iso2: "KG" },
  "Cambodia"                                : { zhName: "Cambodia", currencyCode: "KHR", currencyName: "瑞爾", iso2: "KH" },
  "Kiribati"                                : { zhName: "Kiribati", currencyCode: "AUD", currencyName: "澳幣", iso2: "KI" },
  "Comoros"                                 : { zhName: "Comoros", currencyCode: "KMF", currencyName: "科摩羅法郎", iso2: "KM" },
  "Saint Kitts and Nevis"                   : { zhName: "Saint Kitts and Nevis", currencyCode: "USD", currencyName: "美元", iso2: "KN" },
  "North Korea"                             : { zhName: "North Korea", currencyCode: "KPW", currencyName: "朝鮮圓", iso2: "KP" },
  "South Korea"                             : { zhName: "South Korea", currencyCode: "KRW", currencyName: "韓圓", iso2: "KR" },
  "Kosovo"                                  : { zhName: "Kosovo", currencyCode: "EUR", currencyName: "歐元", iso2: "XK" },
  "Kuwait"                                  : { zhName: "Kuwait", currencyCode: "KWD", currencyName: "科威特第納爾", iso2: "KW" },
  "Cayman Islands"                          : { zhName: "Cayman Islands", currencyCode: "KYD", currencyName: "開曼元", iso2: "KY" },
  "Kazakhstan"                              : { zhName: "Kazakhstan", currencyCode: "KZT", currencyName: "堅戈", iso2: "KZ" },
  "Lao People's Democratic Republic"        : { zhName: "Lao People's Democratic Republic", currencyCode: "LAK", currencyName: "基普", iso2: "LA" },
  "Lebanon"                                 : { zhName: "Lebanon", currencyCode: "LBP", currencyName: "黎巴嫩鎊", iso2: "LB" },
  "Saint Lucia"                             : { zhName: "Saint Lucia", currencyCode: "USD", currencyName: "美元", iso2: "LC" },
  "Liechtenstein"                           : { zhName: "Liechtenstein", currencyCode: "CHF", currencyName: "瑞士法郎", iso2: "LI" },
  "Sri Lanka"                               : { zhName: "Sri Lanka", currencyCode: "LKR", currencyName: "盧比", iso2: "LK" },
  "Liberia"                                 : { zhName: "Liberia", currencyCode: "LRD", currencyName: "賴比瑞亞元", iso2: "LR" },
  "Lesotho"                                 : { zhName: "Lesotho", currencyCode: "LSL", currencyName: "洛蒂", iso2: "LS" },
  "Lithuania"                               : { zhName: "Lithuania", currencyCode: "EUR", currencyName: "歐元", iso2: "LT" },
  "Luxembourg"                              : { zhName: "Luxembourg", currencyCode: "EUR", currencyName: "歐元", iso2: "LU" },
  "Latvia"                                  : { zhName: "Latvia", currencyCode: "EUR", currencyName: "歐元", iso2: "LV" },
  "Libya"                                   : { zhName: "Libya", currencyCode: "LYD", currencyName: "第納爾", iso2: "LY" },
  "Morocco"                                 : { zhName: "Morocco", currencyCode: "MAD", currencyName: "迪拉姆", iso2: "MA" },
  "Monaco"                                  : { zhName: "Monaco", currencyCode: "EUR", currencyName: "歐元", iso2: "MC" },
  "Moldova"                                 : { zhName: "Moldova", currencyCode: "MDL", currencyName: "列伊", iso2: "MD" },
  "Madagascar"                              : { zhName: "Madagascar", currencyCode: "MGA", currencyName: "阿里亞里", iso2: "MG" },
  "Montenegro"                              : { zhName: "Montenegro", currencyCode: "EUR", currencyName: "歐元", iso2: "ME" },
  "Saint Martin"                            : { zhName: "Saint Martin", currencyCode: "EUR", currencyName: "歐元", iso2: "MF" },
  "Marshall Islands"                        : { zhName: "Marshall Islands", currencyCode: "USD", currencyName: "美元", iso2: "MH" },
  "Macedonia"                               : { zhName: "Macedonia", currencyCode: "MKD", currencyName: "第納爾", iso2: "MK" },
  "Mali"                                    : { zhName: "Mali", currencyCode: "XOF", currencyName: "西非法郎", iso2: "ML" },
  "Macau"                                   : { zhName: "Macau", currencyCode: "MOP", currencyName: "澳門幣", iso2: "MO" },
  "Myanmar"                                 : { zhName: "Myanmar", currencyCode: "MMK", currencyName: "緬甸元", iso2: "MM" },
  "Mongolia"                                : { zhName: "Mongolia", currencyCode: "MNT", currencyName: "圖格里克", iso2: "MN" },
  "Northern Mariana Islands"                : { zhName: "Northern Mariana Islands", currencyCode: "USD", currencyName: "美元", iso2: "MP" },
  "Martinique"                              : { zhName: "Martinique", currencyCode: "USD", currencyName: "美元", iso2: "MQ" },
  "Mauritania"                              : { zhName: "Mauritania", currencyCode: "MRU", currencyName: "烏吉亞", iso2: "MR" },
  "Montserrat"                              : { zhName: "Montserrat", currencyCode: "XCD", currencyName: "東加勒比元", iso2: "MS" },
  "Malta"                                   : { zhName: "Malta", currencyCode: "EUR", currencyName: "歐元", iso2: "MT" },
  "Mauritius"                               : { zhName: "Mauritius", currencyCode: "MUR", currencyName: "盧比", iso2: "MU" },
  "Maldives"                                : { zhName: "Maldives", currencyCode: "MVR", currencyName: "拉菲亞", iso2: "MV" },
  "Malawi"                                  : { zhName: "Malawi", currencyCode: "MWK", currencyName: "克瓦查", iso2: "MW" },
  "Mexico"                                  : { zhName: "Mexico", currencyCode: "USD", currencyName: "美元", iso2: "MX" },
  "Malaysia"                                : { zhName: "Malaysia", currencyCode: "MYR", currencyName: "令吉", iso2: "MY" },
  "Mozambique"                              : { zhName: "Mozambique", currencyCode: "MZN", currencyName: "梅蒂卡爾", iso2: "MZ" },
  "Namibia"                                 : { zhName: "Namibia", currencyCode: "NAD", currencyName: "納米比亞元", iso2: "NA" },
  "New Caledonia"                           : { zhName: "New Caledonia", currencyCode: "XPF", currencyName: "太平洋法郎", iso2: "NC" },
  "Niger"                                   : { zhName: "Niger", currencyCode: "XOF", currencyName: "西非法郎", iso2: "NE" },
  "Norfolk Island"                          : { zhName: "Norfolk Island", currencyCode: "AUD", currencyName: "澳幣", iso2: "NF" },
  "Nigeria"                                 : { zhName: "Nigeria", currencyCode: "NGN", currencyName: "奈拉", iso2: "NG" },
  "Nicaragua"                               : { zhName: "Nicaragua", currencyCode: "NIO", currencyName: "美元", iso2: "NI" },
  "Netherlands"                             : { zhName: "Netherlands", currencyCode: "EUR", currencyName: "歐元", iso2: "NL" },
  "Norway"                                  : { zhName: "Norway", currencyCode: "NOK", currencyName: "挪威克朗", iso2: "NO" },
  "Nepal"                                   : { zhName: "Nepal", currencyCode: "NPR", currencyName: "盧比", iso2: "NP" },
  "Nauru"                                   : { zhName: "Nauru", currencyCode: "AUD", currencyName: "澳幣", iso2: "NR" },
  "Niue"                                    : { zhName: "Niue", currencyCode: "NZD", currencyName: "紐幣", iso2: "NU" },
  "New Zealand"                             : { zhName: "New Zealand", currencyCode: "NZD", currencyName: "紐幣", iso2: "NZ" },
  "Oman"                                    : { zhName: "Oman", currencyCode: "OMR", currencyName: "里亞爾", iso2: "OM" },
  "Panama"                                  : { zhName: "Panama", currencyCode: "USD", currencyName: "美元", iso2: "PA" },
  "Peru"                                    : { zhName: "Peru", currencyCode: "USD", currencyName: "美元", iso2: "PE" },
  "French Polynesia"                        : { zhName: "French Polynesia", currencyCode: "XPF", currencyName: "太平洋法郎", iso2: "PF" },
  "Papua New Guinea"                        : { zhName: "Papua New Guinea", currencyCode: "PGK", currencyName: "基那", iso2: "PG" },
  "Philippines"                             : { zhName: "Philippines", currencyCode: "PHP", currencyName: "披索", iso2: "PH" },
  "Pakistan"                                : { zhName: "Pakistan", currencyCode: "PKR", currencyName: "巴基斯坦盧比", iso2: "PK" },
  "Poland"                                  : { zhName: "Poland", currencyCode: "PLN", currencyName: "茲羅提", iso2: "PL" },
  "Saint Pierre and Miquelon"               : { zhName: "Saint Pierre and Miquelon", currencyCode: "EUR", currencyName: "歐元", iso2: "PM" },
  "Pitcairn Islands"                        : { zhName: "Pitcairn Islands", currencyCode: "NZD", currencyName: "紐幣", iso2: "PN" },
  "Puerto Rico"                             : { zhName: "Puerto Rico", currencyCode: "USD", currencyName: "美元", iso2: "PR" },
  "Palestinian Territories"                 : { zhName: "Palestinian Territories", currencyCode: "ILS", currencyName: "新謝克爾", iso2: "PS" },
  "Portugal"                                : { zhName: "Portugal", currencyCode: "EUR", currencyName: "歐元", iso2: "PT" },
  "Palau"                                   : { zhName: "Palau", currencyCode: "USD", currencyName: "美元", iso2: "PW" },
  "Paraguay"                                : { zhName: "Paraguay", currencyCode: "USD", currencyName: "美元", iso2: "PY" },
  "Qatar"                                   : { zhName: "Qatar", currencyCode: "QAR", currencyName: "卡達里亞爾", iso2: "QA" },
  "Reunion"                                 : { zhName: "Reunion", currencyCode: "EUR", currencyName: "歐元", iso2: "RE" },
  "Romania"                                 : { zhName: "Romania", currencyCode: "RON", currencyName: "列伊", iso2: "RO" },
  "Serbia"                                  : { zhName: "Serbia", currencyCode: "RSD", currencyName: "第納爾", iso2: "RS" },
  "Russia"                                  : { zhName: "Russia", currencyCode: "RUB", currencyName: "盧布", iso2: "RU" },
  "Rwanda"                                  : { zhName: "Rwanda", currencyCode: "RWF", currencyName: "法郎", iso2: "RW" },
  "Saudi Arabia"                            : { zhName: "Saudi Arabia", currencyCode: "SAR", currencyName: "里亞爾", iso2: "SA" },
  "Solomon Islands"                         : { zhName: "Solomon Islands", currencyCode: "SBD", currencyName: "所羅門群島元", iso2: "SB" },
  "Seychelles"                              : { zhName: "Seychelles", currencyCode: "SCR", currencyName: "塞席爾盧比", iso2: "SC" },
  "Sudan"                                   : { zhName: "Sudan", currencyCode: "SDG", currencyName: "蘇丹鎊", iso2: "SD" },
  "Sweden"                                  : { zhName: "Sweden", currencyCode: "SEK", currencyName: "瑞典克朗", iso2: "SE" },
  "Singapore"                               : { zhName: "Singapore", currencyCode: "SGD", currencyName: "新幣", iso2: "SG" },
  "Saint Helena"                            : { zhName: "Saint Helena", currencyCode: "SHP", currencyName: "聖赫勒拿鎊", iso2: "SH" },
  "Slovenia"                                : { zhName: "Slovenia", currencyCode: "EUR", currencyName: "歐元", iso2: "SI" },
  "Svalbard and Jan Mayen"                  : { zhName: "Svalbard and Jan Mayen", currencyCode: "NOK", currencyName: "挪威克朗", iso2: "SJ" },
  "Slovakia"                                : { zhName: "Slovakia", currencyCode: "EUR", currencyName: "歐元", iso2: "SK" },
  "Sierra Leone"                            : { zhName: "Sierra Leone", currencyCode: "SLL", currencyName: "利昂", iso2: "SL" },
  "San Marino"                              : { zhName: "San Marino", currencyCode: "EUR", currencyName: "歐元", iso2: "SM" },
  "Senegal"                                 : { zhName: "Senegal", currencyCode: "XOF", currencyName: "西非法郎", iso2: "SN" },
  "Somalia"                                 : { zhName: "Somalia", currencyCode: "SOS", currencyName: "索馬利亞先令", iso2: "SO" },
  "Suriname"                                : { zhName: "Suriname", currencyCode: "USD", currencyName: "美元", iso2: "SR" },
  "South Sudan"                             : { zhName: "South Sudan", currencyCode: "SSP", currencyName: "南蘇丹鎊", iso2: "SS" },
  "Sao Tome and Principe"                   : { zhName: "Sao Tome and Principe", currencyCode: "STN", currencyName: "多布拉", iso2: "ST" },
  "El Salvador"                             : { zhName: "El Salvador", currencyCode: "USD", currencyName: "美元", iso2: "SV" },
  "Saint Martin"                            : { zhName: "Saint Martin", currencyCode: "ANG", currencyName: "荷屬安替列盾", iso2: "SX" },
  "Syria"                                   : { zhName: "Syria", currencyCode: "SYP", currencyName: "敘利亞鎊", iso2: "SY" },
  "Swaziland"                               : { zhName: "Swaziland", currencyCode: "SZL", currencyName: "里蘭吉尼", iso2: "SZ" },
  "Turks and Caicos Islands"                : { zhName: "Turks and Caicos Islands", currencyCode: "USD", currencyName: "美元", iso2: "TC" },
  "Chad"                                    : { zhName: "Chad", currencyCode: "XAF", currencyName: "中非法郎", iso2: "TD" },
  "French Southern and Antarctic Lands"     : { zhName: "French Southern and Antarctic Lands", currencyCode: "EUR", currencyName: "歐元", iso2: "TF" },
  "Togo"                                    : { zhName: "Togo", currencyCode: "XOF", currencyName: "西非法郎", iso2: "TG" },
  "Thailand"                                : { zhName: "Thailand", currencyCode: "THB", currencyName: "泰銖", iso2: "TH" },
  "Tajikistan"                              : { zhName: "Tajikistan", currencyCode: "TJS", currencyName: "索莫尼", iso2: "TJ" },
  "Tokelau"                                 : { zhName: "Tokelau", currencyCode: "NZD", currencyName: "紐幣", iso2: "TK" },
  "Timor-Leste"                             : { zhName: "Timor-Leste", currencyCode: "USD", currencyName: "美元", iso2: "TL" },
  "Turkmenistan"                            : { zhName: "Turkmenistan", currencyCode: "TMT", currencyName: "馬納特", iso2: "TM" },
  "Tunisia"                                 : { zhName: "Tunisia", currencyCode: "TND", currencyName: "突尼西亞第納爾", iso2: "TN" },
  "Tonga"                                   : { zhName: "Tonga", currencyCode: "TOP", currencyName: "潘加", iso2: "TO" },
  "Turkey"                                  : { zhName: "Turkey", currencyCode: "TRY", currencyName: "里拉", iso2: "TR" },
  "Trinidad and Tobago"                     : { zhName: "Trinidad and Tobago", currencyCode: "USD", currencyName: "美元", iso2: "TT" },
  "Tuvalu"                                  : { zhName: "Tuvalu", currencyCode: "AUD", currencyName: "澳幣", iso2: "TV" },
  "Taiwan"                                  : { zhName: "Taiwan", currencyCode: "TWD", currencyName: "TWD", iso2: "TW" },
  "Tanzania"                                : { zhName: "Tanzania", currencyCode: "TZS", currencyName: "先令", iso2: "TZ" },
  "Ukraine"                                 : { zhName: "Ukraine", currencyCode: "UAH", currencyName: "格里夫納", iso2: "UA" },
  "Uganda"                                  : { zhName: "ganda", currencyCode: "UGX", currencyName: "先令", iso2: "UG" },
  "Jarvis Island"                           : { zhName: "Jarvis Island", currencyCode: "USD", currencyName: "美元", iso2: "UM-DQ" },
  "Baker Island"                            : { zhName: "Baker Island", currencyCode: "USD", currencyName: "美元", iso2: "UM-FQ" },
  "Howland Island"                          : { zhName: "Howland Island", currencyCode: "USD", currencyName: "美元", iso2: "UM-HQ" },
  "Johnston Atoll"                          : { zhName: "Johnston Atoll", currencyCode: "USD", currencyName: "美元", iso2: "UM-JQ" },
  "Midway Islands"                          : { zhName: "Midway Islands", currencyCode: "USD", currencyName: "美元", iso2: "UM-MQ" },
  "Wake Island"                             : { zhName: "Wake Island", currencyCode: "USD", currencyName: "美元", iso2: "UM-WQ" },
  "United States"                           : { zhName: "United States", currencyCode: "USD", currencyName: "美元", iso2: "US" },
  "Uruguay"                                 : { zhName: "Uruguay", currencyCode: "USD", currencyName: "美元", iso2: "UY" },
  "Uzbekistan"                              : { zhName: "Uzbekistan", currencyCode: "UZS", currencyName: "蘇姆", iso2: "UZ" },
  "Vatican City"                            : { zhName: "Vatican City", currencyCode: "EUR", currencyName: "歐元", iso2: "VA" },
  "Saint Vincent and the Grenadines"        : { zhName: "Saint Vincent and the Grenadines", currencyCode: "XCD", currencyName: "美元", iso2: "VC" },
  "Venezuela"                               : { zhName: "Venezuela", currencyCode: "USD", currencyName: "美元", iso2: "VE" },
  "British Virgin Islands"                  : { zhName: "British Virgin Islands", currencyCode: "USD", currencyName: "美元", iso2: "VG" },
  "US Virgin Islands"                       : { zhName: "US Virgin Islands", currencyCode: "USD", currencyName: "美元", iso2: "VI" },
  "Vietnam"                                 : { zhName: "Vietnam", currencyCode: "VND", currencyName: "越南盾", iso2: "VN" },
  "Vanuatu"                                 : { zhName: "Vanuatu", currencyCode: "VUV", currencyName: "瓦圖", iso2: "VU" },
  "Wallis and Futuna"                       : { zhName: "Wallis and Futuna", currencyCode: "XPF", currencyName: "太平洋法郎", iso2: "WF" },
  "Samoa"                                   : { zhName: "Samoa", currencyCode: "WST", currencyName: "塔拉", iso2: "WS" },
  "Yemen"                                   : { zhName: "Yemen", currencyCode: "YER", currencyName: "里亞爾", iso2: "YE" },
  "Mayotte"                                 : { zhName: "Mayotte", currencyCode: "EUR", currencyName: "歐元", iso2: "YT" },
  "South Africa"                            : { zhName: "South Africa", currencyCode: "ZAR", currencyName: "蘭特", iso2: "ZA" },
  "Zambia"                                  : { zhName: "Zambia", currencyCode: "ZMW", currencyName: "克瓦查", iso2: "ZM" },
  "Zimbabwe"                                : { zhName: "Zimbabwe", currencyCode: "ZWL", currencyName: "辛巴威元", iso2: "ZW" },
};

window.getCountryInfo = function(enName){
  const d = (window.COUNTRY_INFO && window.COUNTRY_INFO[enName]) || null;
  return d ? d: { zhName: enName, currencyCode: "—", currencyName: "—", iso2: null };
};